extends Node
## AudioManager — every sound the game makes (autoload, last).
##
## Listens to EventBus and nothing else. No UI script asks for a sound, which
## is why adding audio to a finished game touched no screen: the events that
## deserve a sound were already being emitted for the UI to react to.
##
## Sounds are generated by tools/make_audio.py — see that file for the design
## rules behind them.

## Voices per sound. Four is enough for the tap to overlap itself at the
## fastest attack speed in the game without cutting its own tail off.
const VOICES: int = 4

## Minimum gap between two plays of the SAME sound, in seconds.
##
## Layering a clip over itself does not make it twice as loud, it makes it
## clip: every sound peaks at 0.72, and two in the same frame is 1.44 into a
## bus that stops at 1.0. That is not hypothetical — CombatManager emits
## boss_fight_won, WorldManager answers that signal by emitting world_unlocked,
## and both map to the fanfare, so beating a world boss distorted the single
## biggest moment the game has.
##
## Sounds gap independently of each other. A crit landing 10ms after a tap
## still plays both, because two different sounds read as variety; it is one
## sound repeating that reads as a fault.
const REPEAT_GAP: Dictionary = {
	# Swift Hunt plus Twin Fang drives the auto-attacker faster than the tap
	# can decay. Twenty taps a second is a buzz, not feedback, and it is the
	# fastest way to make someone mute a game.
	&"tap": 0.055,
	# Kills arrive in bursts at high attack speed for the same reason.
	&"death": 0.12,
	# Long, loud, and triggered by two separate events on one frame.
	&"fanfare": 0.4,
	&"boss": 0.4,
	# A kill can drop an item, a relic and a pet at once.
	&"loot": 0.06,
}
## Enough to stop one frame's duplicates without ever being audible as a
## dropped sound.
const DEFAULT_REPEAT_GAP: float = 0.03

## Per-shot pitch jitter. Without it a held finger produces the same 70ms
## sample forty times in a row, which stops reading as impact and starts
## reading as a fault.
const PITCH_JITTER: float = 0.08

const SFX: Dictionary = {
	&"tap": "res://audio/sfx/tap_hit.wav",
	&"crit": "res://audio/sfx/crit_hit.wav",
	&"death": "res://audio/sfx/enemy_death.wav",
	&"boss": "res://audio/sfx/boss_defeat.wav",
	&"fanfare": "res://audio/sfx/fanfare.wav",
	&"confirm": "res://audio/sfx/confirm.wav",
	&"loot": "res://audio/sfx/loot.wav",
}
const MUSIC_PATH: String = "res://audio/music/ambient_void.wav"

## sound id -> Array[AudioStreamPlayer]
var _voices: Dictionary = {}
var _next_voice: Dictionary = {}
var _music: AudioStreamPlayer

## sound id -> Time.get_ticks_msec() of its last play.
var _last_played_msec: Dictionary = {}

## Where the drone had got to when the app was backgrounded, so resuming picks
## the loop up rather than restarting its swell from the top every time the
## player glances at a notification.
var _music_position: float = 0.0


func _ready() -> void:
	# Sound must keep playing while the tree is paused (the offline modal and
	# every confirm scrim pause it), or a purchase made from a modal is silent.
	process_mode = Node.PROCESS_MODE_ALWAYS
	_build_voices()
	_build_music()
	_connect_events()


func _notification(what: int) -> void:
	match what:
		# Android home button / app switch. NOTHING else in the game stops the
		# music: PROCESS_MODE_ALWAYS means pausing the tree does not, and a
		# LOOP_FORWARD stream has no end to reach on its own. Without this the
		# drone follows the player out of the app and plays over whatever they
		# opened next, until they force-quit the game.
		NOTIFICATION_APPLICATION_PAUSED:
			suspend()
		NOTIFICATION_APPLICATION_RESUMED:
			resume()
		NOTIFICATION_WM_CLOSE_REQUEST, NOTIFICATION_EXIT_TREE:
			_shutdown()


func _build_voices() -> void:
	for id: StringName in SFX:
		var stream: AudioStream = load(SFX[id])
		if stream == null:
			push_error("AudioManager: missing sound %s" % SFX[id])
			continue
		var pool: Array[AudioStreamPlayer] = []
		for _i: int in VOICES:
			var player := AudioStreamPlayer.new()
			player.stream = stream
			player.bus = &"SFX"
			player.process_mode = Node.PROCESS_MODE_ALWAYS
			add_child(player)
			pool.append(player)
		_voices[id] = pool
		_next_voice[id] = 0


func _build_music() -> void:
	var stream: AudioStream = load(MUSIC_PATH)
	if stream == null:
		push_error("AudioManager: missing music %s" % MUSIC_PATH)
		return
	# The .wav imports as a one-shot; the loop points are set here rather than
	# in the .import so the intent lives beside the code that depends on it.
	# duplicate() first — the imported resource is shared, and editing it in
	# place would leak this setting into anything else that loads the file.
	var looping: AudioStreamWAV = stream.duplicate()
	if looping is AudioStreamWAV:
		looping.loop_mode = AudioStreamWAV.LOOP_FORWARD
		looping.loop_begin = 0
		# In samples, and it must be the real end. Left at its default of 0
		# this is a zero-length loop, not "play to the end" — the track starts
		# and stops in the same frame, and the only symptom is silence, which
		# is indistinguishable from the game having no music at all.
		looping.loop_end = int(looping.get_length() * float(looping.mix_rate))
	_music = AudioStreamPlayer.new()
	_music.stream = looping
	_music.bus = &"Music"
	_music.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(_music)
	_music.play()


func _connect_events() -> void:
	EventBus.enemy_damaged.connect(_on_enemy_damaged)
	EventBus.enemy_died.connect(_on_enemy_died)
	EventBus.boss_fight_won.connect(_on_boss_won)
	# Earned moments. All rare, all worth the same fanfare — a player should
	# learn one sound that means "you got something permanent".
	EventBus.world_unlocked.connect(func(_world: WorldDefinition) -> void: play(&"fanfare"))
	EventBus.auto_attack_unlocked.connect(func() -> void: play(&"fanfare"))
	EventBus.relics_awakened.connect(func() -> void: play(&"fanfare"))
	EventBus.pet_evolved.connect(func(_id: StringName, _stage: int) -> void: play(&"fanfare"))
	EventBus.eclipse_performed.connect(
		func(_reward: float, _count: int) -> void: play(&"fanfare")
	)
	# Acquisitions.
	EventBus.item_dropped.connect(func(_item: Dictionary) -> void: play(&"loot"))
	EventBus.relic_dropped.connect(func(_id: StringName) -> void: play(&"loot"))
	EventBus.pet_unlocked.connect(func(_id: StringName) -> void: play(&"loot"))
	# Deliberate actions the player took, which need a confirmation they landed.
	EventBus.upgrade_purchased.connect(
		func(_id: StringName, _level: int) -> void: play(&"confirm")
	)
	EventBus.item_equipped.connect(func(_slot: StringName) -> void: play(&"confirm"))
	EventBus.skill_purchased.connect(
		func(_id: StringName, _level: int) -> void: play(&"confirm")
	)
	EventBus.active_relic_changed.connect(func(_id: StringName) -> void: play(&"confirm"))
	EventBus.cosmetic_equipped.connect(func(_id: StringName) -> void: play(&"confirm"))
	EventBus.purchase_completed.connect(func(_id: StringName) -> void: play(&"confirm"))


# --- Public -------------------------------------------------------------------


## Silence everything and remember where the music was. Public because the
## logic harness drives it directly — the Android lifecycle notifications it
## normally answers cannot be raised from a headless desktop run.
func suspend() -> void:
	if _music != null and _music.playing:
		_music_position = _music.get_playback_position()
		_music.stop()
	for id: StringName in _voices:
		for player: AudioStreamPlayer in _voices[id]:
			player.stop()


## Pick the drone back up where it left off. One-shots are not resumed: a hit
## sound the player never heard is not worth playing three minutes late.
func resume() -> void:
	if _music != null and not _music.playing:
		_music.play(_music_position)


## Stop, then hand the streams back.
##
## Clearing `stream` drops this side's reference immediately rather than
## leaving it to whenever the player node is finally freed. The AudioServer
## still releases the playback on its own schedule — it needs one mix step to
## do it — so on the quit path, where no further frame runs, the pair is
## reported as leaked no matter what happens here. Measured, not assumed: this
## function demonstrably runs, and the exit-time warning survives it.
##
## It earns its place on the desktop close path, where NOTIFICATION_WM_CLOSE_-
## REQUEST arrives with frames still to come and the release does complete.
func _shutdown() -> void:
	suspend()
	if _music != null:
		_music.stream = null
	for id: StringName in _voices:
		for player: AudioStreamPlayer in _voices[id]:
			player.stream = null


## Play a sound by id. Drops a repeat of the same sound inside its REPEAT_GAP,
## round-robins the voice pool so a sound never cuts its own tail, and jitters
## pitch so repeats do not sound mechanical.
func play(id: StringName, pitch: float = 1.0) -> void:
	var pool: Array = _voices.get(id, [])
	if pool.is_empty():
		return
	var now: int = Time.get_ticks_msec()
	var gap: float = REPEAT_GAP.get(id, DEFAULT_REPEAT_GAP)
	if now - int(_last_played_msec.get(id, -100000)) < int(gap * 1000.0):
		return
	_last_played_msec[id] = now
	var index: int = int(_next_voice[id])
	_next_voice[id] = (index + 1) % pool.size()
	var player: AudioStreamPlayer = pool[index]
	player.pitch_scale = pitch * (1.0 + randf_range(-PITCH_JITTER, PITCH_JITTER))
	player.play()


# --- Handlers -----------------------------------------------------------------


func _on_enemy_damaged(_amount: float, is_crit: bool, _hp: float, _max_hp: float) -> void:
	# No rate limiting here any more — play() gaps each sound against itself.
	# A crit therefore still lands even in the middle of a stream of taps,
	# which matters: it is the moment worth hearing, and suppressing it would
	# mean the bigger the fight, the less the payoff registers.
	play(&"crit" if is_crit else &"tap")


func _on_enemy_died(_level: int, _total_kills: int) -> void:
	play(&"death")


func _on_boss_won(_level: int, _payout: float, is_world_boss: bool) -> void:
	play(&"boss")
	if is_world_boss:
		play(&"fanfare")
