extends Node
## AudioManager — every sound the game makes (autoload, last).
##
## Listens to EventBus and nothing else. No UI script asks for a sound, which
## is why adding audio to a finished game touched no screen: the events that
## deserve a sound were already being emitted for the UI to react to.
##
## Sounds are generated by tools/make_audio.py — see that file for the design
## rules behind them.

## Voices per sound. Four is enough for the tap to overlap itself at the
## fastest attack speed in the game without cutting its own tail off.
const VOICES: int = 4

## The tap fires on every attack, and Swift Hunt plus Twin Fang can drive the
## auto-attacker faster than a sound can decay. Below this gap the hit is
## skipped entirely rather than layered — twenty taps a second is a buzz, not
## feedback, and it is also the fastest way to make someone mute a game.
const MIN_HIT_GAP: float = 0.055
## Kills come in bursts at high attack speed for the same reason.
const MIN_DEATH_GAP: float = 0.12

## Per-shot pitch jitter. Without it a held finger produces the same 70ms
## sample forty times in a row, which stops reading as impact and starts
## reading as a fault.
const PITCH_JITTER: float = 0.08

const SFX: Dictionary = {
	&"tap": "res://audio/sfx/tap_hit.wav",
	&"crit": "res://audio/sfx/crit_hit.wav",
	&"death": "res://audio/sfx/enemy_death.wav",
	&"boss": "res://audio/sfx/boss_defeat.wav",
	&"fanfare": "res://audio/sfx/fanfare.wav",
	&"confirm": "res://audio/sfx/confirm.wav",
	&"loot": "res://audio/sfx/loot.wav",
}
const MUSIC_PATH: String = "res://audio/music/ambient_void.wav"

## sound id -> Array[AudioStreamPlayer]
var _voices: Dictionary = {}
var _next_voice: Dictionary = {}
var _music: AudioStreamPlayer

var _last_hit_msec: int = 0
var _last_death_msec: int = 0


func _ready() -> void:
	# Sound must keep playing while the tree is paused (the offline modal and
	# every confirm scrim pause it), or a purchase made from a modal is silent.
	process_mode = Node.PROCESS_MODE_ALWAYS
	_build_voices()
	_build_music()
	_connect_events()


func _build_voices() -> void:
	for id: StringName in SFX:
		var stream: AudioStream = load(SFX[id])
		if stream == null:
			push_error("AudioManager: missing sound %s" % SFX[id])
			continue
		var pool: Array[AudioStreamPlayer] = []
		for _i: int in VOICES:
			var player := AudioStreamPlayer.new()
			player.stream = stream
			player.bus = &"SFX"
			player.process_mode = Node.PROCESS_MODE_ALWAYS
			add_child(player)
			pool.append(player)
		_voices[id] = pool
		_next_voice[id] = 0


func _build_music() -> void:
	var stream: AudioStream = load(MUSIC_PATH)
	if stream == null:
		push_error("AudioManager: missing music %s" % MUSIC_PATH)
		return
	# The .wav imports as a one-shot; the loop points are set here rather than
	# in the .import so the intent lives beside the code that depends on it.
	# duplicate() first — the imported resource is shared, and editing it in
	# place would leak this setting into anything else that loads the file.
	var looping: AudioStreamWAV = stream.duplicate()
	if looping is AudioStreamWAV:
		looping.loop_mode = AudioStreamWAV.LOOP_FORWARD
		looping.loop_begin = 0
		# In samples, and it must be the real end. Left at its default of 0
		# this is a zero-length loop, not "play to the end" — the track starts
		# and stops in the same frame, and the only symptom is silence, which
		# is indistinguishable from the game having no music at all.
		looping.loop_end = int(looping.get_length() * float(looping.mix_rate))
	_music = AudioStreamPlayer.new()
	_music.stream = looping
	_music.bus = &"Music"
	_music.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(_music)
	_music.play()


func _connect_events() -> void:
	EventBus.enemy_damaged.connect(_on_enemy_damaged)
	EventBus.enemy_died.connect(_on_enemy_died)
	EventBus.boss_fight_won.connect(_on_boss_won)
	# Earned moments. All rare, all worth the same fanfare — a player should
	# learn one sound that means "you got something permanent".
	EventBus.world_unlocked.connect(func(_world: WorldDefinition) -> void: play(&"fanfare"))
	EventBus.auto_attack_unlocked.connect(func() -> void: play(&"fanfare"))
	EventBus.relics_awakened.connect(func() -> void: play(&"fanfare"))
	EventBus.pet_evolved.connect(func(_id: StringName, _stage: int) -> void: play(&"fanfare"))
	EventBus.eclipse_performed.connect(
		func(_reward: float, _count: int) -> void: play(&"fanfare")
	)
	# Acquisitions.
	EventBus.item_dropped.connect(func(_item: Dictionary) -> void: play(&"loot"))
	EventBus.relic_dropped.connect(func(_id: StringName) -> void: play(&"loot"))
	EventBus.pet_unlocked.connect(func(_id: StringName) -> void: play(&"loot"))
	# Deliberate actions the player took, which need a confirmation they landed.
	EventBus.upgrade_purchased.connect(
		func(_id: StringName, _level: int) -> void: play(&"confirm")
	)
	EventBus.item_equipped.connect(func(_slot: StringName) -> void: play(&"confirm"))
	EventBus.skill_purchased.connect(
		func(_id: StringName, _level: int) -> void: play(&"confirm")
	)
	EventBus.active_relic_changed.connect(func(_id: StringName) -> void: play(&"confirm"))
	EventBus.cosmetic_equipped.connect(func(_id: StringName) -> void: play(&"confirm"))
	EventBus.purchase_completed.connect(func(_id: StringName) -> void: play(&"confirm"))


# --- Public -------------------------------------------------------------------


## Play a sound by id. Round-robins the voice pool so a sound never cuts its
## own tail, and jitters pitch so repeats do not sound mechanical.
func play(id: StringName, pitch: float = 1.0) -> void:
	var pool: Array = _voices.get(id, [])
	if pool.is_empty():
		return
	var index: int = int(_next_voice[id])
	_next_voice[id] = (index + 1) % pool.size()
	var player: AudioStreamPlayer = pool[index]
	player.pitch_scale = pitch * (1.0 + randf_range(-PITCH_JITTER, PITCH_JITTER))
	player.play()


# --- Handlers -----------------------------------------------------------------


func _on_enemy_damaged(_amount: float, is_crit: bool, _hp: float, _max_hp: float) -> void:
	var now: int = Time.get_ticks_msec()
	# A crit is always heard: it is the moment worth hearing, and rate-limiting
	# it away would mean the louder the fight, the less the payoff registers.
	if not is_crit and now - _last_hit_msec < int(MIN_HIT_GAP * 1000.0):
		return
	_last_hit_msec = now
	play(&"crit" if is_crit else &"tap")


func _on_enemy_died(_level: int, _total_kills: int) -> void:
	var now: int = Time.get_ticks_msec()
	if now - _last_death_msec < int(MIN_DEATH_GAP * 1000.0):
		return
	_last_death_msec = now
	play(&"death")


func _on_boss_won(_level: int, _payout: float, is_world_boss: bool) -> void:
	play(&"boss")
	if is_world_boss:
		play(&"fanfare")
