using UnityEngine;

namespace VantaEclipse.UI
{
    /// <summary>
    /// The game's one typeface.
    ///
    /// VantaPixel is a hand-authored 5x7 bitmap face on a 9px glyph box,
    /// generated by tools/make_font.py and turned into a Unity Font asset by the
    /// PixelFontImporter. Every font size in the game is a whole multiple of
    /// that box (18 / 27 / 54), because a bitmap face asked for a size that is
    /// not a whole multiple gets resampled, and resampling is exactly what pixel
    /// art exists to avoid. <see cref="VantaTheme.SnapFontSize"/> is what
    /// enforces it; this is what the sizes are multiples OF.
    ///
    /// The fallback is Unity's built-in Arial. It exists so a project with the
    /// font asset not yet generated still renders readable text instead of
    /// nothing — but it is a smooth vector face at arbitrary sizes, so anything
    /// that renders through it is visibly wrong rather than subtly wrong, which
    /// is the intent.
    /// </summary>
    public static class Fonts
    {
        public const string ResourcePath = "Fonts/VantaPixel";
        /// <summary>The size the face is authored at, and the size every
        /// requested size must be a multiple of.</summary>
        public const int NativeSize = 9;

        static Font _body;
        static bool _warned;

        public static Font Body
        {
            get
            {
                if (_body != null) return _body;

                _body = Resources.Load<Font>(ResourcePath);
                if (_body == null)
                {
                    if (!_warned)
                    {
                        _warned = true;
                        Debug.LogWarning(
                            $"Fonts: no pixel face at Resources/{ResourcePath} — falling back to " +
                            "Arial. Run Vanta Eclipse > Build Pixel Font.");
                    }
                    _body = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
                }
                return _body;
            }
        }
    }
}
