// GENERATED by tools/port/port_data.py from scripts/data/ad_placement_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/AdPlacementDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// One opt-in rewarded-ad offer. Adding or retuning a placement is a .tres.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Ad Placement", fileName = "NewAdPlacementDefinition")]
    public partial class AdPlacementDefinition : ScriptableObject
    {
        public enum RewardKind
        {
            ESSENCE_SECONDS,
            ARCADE_TOKENS,
            MULTIPLY_PENDING,
        }

        public string id = "";
        public string displayName = "";
        public string description = "";
        public RewardKind rewardKind = RewardKind.ESSENCE_SECONDS;
        public float rewardAmount = 600.0f;
        public int dailyCap = 3;
        public bool contextual = false;
        public int sortOrder = 0;
    }
}
