// GENERATED by tools/port/port_data.py from scripts/data/affix_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/AffixDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// One rollable equipment affix. The affix pool is data — new affixes are new
    /// .tres files, no code change.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Affix", fileName = "NewAffixDefinition")]
    public partial class AffixDefinition : ScriptableObject
    {
        public string id = "";
        public string stat = "";
        public string displayTemplate = "{value}";
        public float minValue = 0.0f;
        public float maxValue = 1.0f;
        public bool isPercent = true;
        public float levelScale = 0.0f;
    }
}
