// GENERATED by tools/port/port_data.py from scripts/data/cosmetic_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/CosmeticDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// A tap-trail cosmetic. Cosmetics live where NO state is encoded — the tap
    /// impact and its damage numbers — so they can reuse family hues freely
    /// without touching the accent scope law.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Cosmetic", fileName = "NewCosmeticDefinition")]
    public partial class CosmeticDefinition : ScriptableObject
    {
        public string id = "";
        public string displayName = "";
        public Color trailColor = new Color(1f, 0.231f, 0.188f, 1f);
        public Color numberColor = new Color(0.929f, 0.929f, 0.941f, 1f);
        public float shardPrice = 0.0f;
        public int sortOrder = 0;
    }
}
