// GENERATED by tools/port/port_data.py from scripts/data/enemy_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/EnemyDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// Data asset describing one enemy type. Designers add new enemies by
    /// creating a .tres file in data/enemies/ — no code changes needed. Note: a
    /// world names its own roster via WorldDefinition.enemy_definition_paths
    /// rather than each enemy naming its world, and loot is generated from the
    /// kill LEVEL by EquipmentManager rather than a per-enemy table. Both were
    /// considered here and deliberately solved on the other side.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Enemy", fileName = "NewEnemyDefinition")]
    public partial class EnemyDefinition : ScriptableObject
    {
        public string id = "";
        public string displayName = "";
        public Sprite texture = null;
        public float hpMultiplier = 1.0f;
        public Color glowColor = new Color(0.769f, 0.769f, 0.804f, 1f);
        public bool isBoss = false;
        public float viewScale = 1.0f;
    }
}
