// GENERATED by tools/port/port_data.py from scripts/data/minigame_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/MinigameDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// Data asset describing one Arcade minigame. Designers add a minigame by
    /// writing a scene whose root extends Minigame and dropping a .tres here —
    /// the Arcade hub and the host build themselves from these, so the framework
    /// never changes to gain a game.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Minigame", fileName = "NewMinigameDefinition")]
    public partial class MinigameDefinition : ScriptableObject
    {
        public string id = "";
        public string displayName = "";
        public string description = "";
        public Sprite icon = null;
        public string scenePath = "";
        public int unlockLevel = 20;
        public float rewardSeconds = 240.0f;
        public int tokenCost = 1;
        public bool lowerIsBetter = false;
        public string context = "{}";
        public int sortOrder = 0;
    }
}
