// GENERATED by tools/port/port_data.py from scripts/data/pet_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/PetDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// One pet line — a companion that levels and evolves through stages, each
    /// granting one passive bonus that scales with level.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Pet", fileName = "NewPetDefinition")]
    public partial class PetDefinition : ScriptableObject
    {
        public string id = "";
        public string[] stageNames = new string[0];
        public Sprite[] stageSprites = new Sprite[0];
        public int[] evolutionLevels = new int[0];
        public string bonusStat = "";
        public float bonusPerLevel = 0.02f;
        public int maxLevel = 30;
    }
}
