// GENERATED by tools/port/port_data.py from scripts/data/quest_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/QuestDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// Data asset describing one Journal goal — a quest, a daily, or an
    /// achievement. All three kinds share this shape, so new content of any kind
    /// is a .tres in data/quests/ and never a code change.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Quest", fileName = "NewQuestDefinition")]
    public partial class QuestDefinition : ScriptableObject
    {
        public enum Kind
        {
            QUEST,
            DAILY,
            ACHIEVEMENT,
        }

        public enum MetricShape
        {
            CUMULATIVE,
            SNAPSHOT,
        }

        public enum RewardKind
        {
            ESSENCE_SECONDS,
            ARCADE_TOKENS,
            VOID_CRYSTALS,
            ASTRAL_SHARDS,
        }

        public string id = "";
        public string displayName = "";
        public string description = "";
        public Kind kind = Kind.ACHIEVEMENT;
        public string metric = "";
        public MetricShape metricShape = MetricShape.CUMULATIVE;
        public float target = 1.0f;
        public RewardKind rewardKind = RewardKind.ESSENCE_SECONDS;
        public float rewardAmount = 120.0f;
        public int sortOrder = 0;
    }
}
