// GENERATED by tools/port/port_data.py from scripts/data/relic_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/RelicDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// One relic — a unique, named, permanent coded effect. Not affix gear.
    /// Adding a relic is one .tres; only a NEW effect_id needs manager code.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Relic", fileName = "NewRelicDefinition")]
    public partial class RelicDefinition : ScriptableObject
    {
        public string id = "";
        public string displayName = "";
        public Sprite sigil = null;
        public string effectId = "";
        public float effectValue = 0.0f;
        public string effectDescription = "";
        public string flavor = "";
        public float dropWeight = 1.0f;
    }
}
