// GENERATED by tools/port/port_data.py from scripts/data/shop_product_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/ShopProductDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// One purchasable product. `store_id` is the SKU a real store would use; the
    /// stub billing provider ignores it.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Shop Product", fileName = "NewShopProductDefinition")]
    public partial class ShopProductDefinition : ScriptableObject
    {
        public enum Kind
        {
            ENTITLEMENT,
            BUNDLE,
            SHARDS,
        }

        public string id = "";
        public string storeId = "";
        public string displayName = "";
        public string description = "";
        public Kind kind = Kind.BUNDLE;
        public string priceText = "$2.99";
        public float crystals = 0.0f;
        public int tokens = 0;
        public float shards = 0.0f;
        public string cosmeticId = "";
        public int sortOrder = 0;
    }
}
