// GENERATED by tools/port/port_data.py from scripts/data/skill_node_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/SkillNodeDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// Data asset describing one Ascendant Power (skill-tree node). Designers add
    /// powers by dropping a .tres in data/skills/ — the Eclipse screen builds its
    /// POWERS panel from these, grouped by branch. A node either adds
    /// value_per_level to a stat every level (ADDITIVE) or is a one-level
    /// permanent toggle (FLAG). SkillTreeManager sums/reads them, and the bonuses
    /// layer into PlayerStats / IdleManager exactly as relics and pets do.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Skill Node", fileName = "NewSkillNodeDefinition")]
    public partial class SkillNodeDefinition : ScriptableObject
    {
        public enum EffectKind
        {
            ADDITIVE,
            FLAG,
        }

        public string id = "";
        public string branch = "";
        public string displayName = "";
        public string description = "";
        public EffectKind effectKind = EffectKind.ADDITIVE;
        public string effectStat = "";
        public float valuePerLevel = 0.0f;
        public bool displayAsPercent = false;
        public float baseCost = 4.0f;
        public float costGrowth = 1.55f;
        public int maxLevel = 1;
        public string prereqId = "";
        public int prereqLevel = 1;
        public int sortOrder = 0;
    }
}
