// GENERATED by tools/port/port_data.py from scripts/data/slot_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/SlotDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// One equipment slot. Data-driven so the slot set is content, not code.
    [CreateAssetMenu(menuName = "Vanta Eclipse/Slot", fileName = "NewSlotDefinition")]
    public partial class SlotDefinition : ScriptableObject
    {
        public string id = "";
        public string displayName = "";
        public Sprite icon = null;
        public bool @sealed = false;
        public string sealedFlavor = "";
    }
}
