// GENERATED by tools/port/port_data.py from scripts/data/upgrade_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/UpgradeDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// Data asset describing one shop upgrade. Designers add upgrades by creating
    /// a .tres file in data/upgrades/ — the shop UI builds itself from these. An
    /// upgrade modifies one player stat, either: ADDITIVE — each level adds
    /// value_per_level to the stat directly PERCENT — each level adds
    /// value_per_level to a percentage multiplier (0.10 at level 3 means the stat
    /// is multiplied by 1.30)
    [CreateAssetMenu(menuName = "Vanta Eclipse/Upgrade", fileName = "NewUpgradeDefinition")]
    public partial class UpgradeDefinition : ScriptableObject
    {
        public enum ModifierType
        {
            ADDITIVE,
            PERCENT,
        }

        public string id = "";
        public string displayName = "";
        public string description = "";
        public string stat = "";
        public ModifierType modifierType = ModifierType.ADDITIVE;
        public float valuePerLevel = 1.0f;
        public bool displayAsPercent = false;
        public float baseCost = 5.0f;
        public float costGrowth = 1.15f;
        public int maxLevel = 0;
        public int sortOrder = 0;
    }
}
