// GENERATED by tools/port/port_data.py from scripts/data/world_definition.gd
// Do not edit by hand: edit the Godot definition and re-run the porter, or
// delete the porter once the Godot tree is gone and this becomes the source.
//
// These are `partial` because the Godot definitions carried methods as well as
// fields (get_cost, format_effect, ...) and those cannot be derived from an
// @export list. They live in Methods/WorldDefinition.Methods.cs and survive
// regeneration.
using UnityEngine;

namespace VantaEclipse.Data
{

    /// Data asset describing one 50-level world. Adding a world is a data drop:
    /// one .tres here, creature/boss definitions, and sprites.
    [CreateAssetMenu(menuName = "Vanta Eclipse/World", fileName = "NewWorldDefinition")]
    public partial class WorldDefinition : ScriptableObject
    {
        public string id = "";
        public string displayName = "";
        public int firstLevel = 1;
        public string[] enemyDefinitionPaths = new string[0];
        public string[] bossDefinitionPaths = new string[0];
        public float essenceMultiplier = 1.0f;
    }
}
