#!/usr/bin/env python3
"""Generate the public GitHub Pages site and the README's fact block.

WHY THIS IS GENERATED RATHER THAN WRITTEN

Documentation rots faster than anything else in a project, silently, because
nothing about changing code makes anyone reread a sentence. This repository has
the receipts: the README claimed 19 autoloads after the twentieth landed, the
architecture doc explained in the present tense how the renderer derives
surface normals from an alpha channel the project no longer has, the release
checklist said the game had no audio while sixteen sound files sat in audio/,
and the GitHub Pages site was still serving #FF3B30 on #0B0B0D — two colours
that do not exist in the sixteen-colour palette everything else was rebuilt
around, next to a smooth vector eclipse in a game with no vectors left in it.

Every one of those was true when written. That is the point: correctness at
authoring time is not a property that lasts, so the durable fix is not to write
more carefully but to stop writing the perishable parts by hand.

So the numbers come from the code that defines them — the autoload count from
BuildAndroid.cs, the palette size from pixelart.py, the glyph count from the font
itself — and tools/check_docs.py fails the sweep when what is committed differs
from what this produces. "Remember to update the docs" is not a mechanism.
"The build goes red" is.

WHAT IS AND IS NOT GENERATED

  docs/index.html          fully generated — it is a landing page, all of it
                           derived from the palette, the icon and the listing.
  docs/privacy-policy.html only its <style> block. The legal text is written by
                           a human and must stay that way; the styling has no
                           business drifting off-palette.
  README.md                only the block between the generated markers. Prose
                           outside them is authored and is left alone.

Run: python tools/make_docs.py
"""

import base64
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from pixelart import PALETTE  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent

BEGIN = "<!-- generated by tools/make_docs.py — do not edit between these markers -->"
END = "<!-- end generated -->"


# --- facts --------------------------------------------------------------------
#
# Each one is read from the artefact that DEFINES it, never from another
# document. A number copied between two documents is a number that can disagree
# with itself, which is the failure this whole file exists to prevent.


def facts() -> dict[str, object]:
    build = (ROOT / "Assets/Editor/BuildAndroid.cs").read_text(encoding="utf-8")
    version_txt = (ROOT / "ProjectSettings/ProjectVersion.txt").read_text(encoding="utf-8")
    font = (ROOT / "Assets/Resources/Fonts/vanta_pixel.fnt").read_text(encoding="utf-8")
    sweep = (ROOT / "tools/validate_all.sh").read_text(encoding="utf-8")
    locator = (ROOT / "Assets/Scripts/Core/Game.cs").read_text(encoding="utf-8")
    settings = (ROOT / "ProjectSettings/EditorBuildSettings.asset").read_text(encoding="utf-8")

    return {
        # Every player-facing number is read from the artefact that DEFINES it,
        # never from another document. A number copied between two documents is
        # a number that can disagree with itself.
        "version": _one(r'VersionName\s*=\s*"([^"]+)"', build),
        "unity": _one(r"m_EditorVersion:\s*(\S+)", version_txt),
        "target_sdk": _one(r"TargetSdk\s*=\s*(?:\(AndroidSdkVersions\))?(?:AndroidSdkVersions\.AndroidApiLevel)?(\d+)", build),
        "min_sdk": _one(r"MinSdk\s*=\s*(?:\(AndroidSdkVersions\))?(?:AndroidSdkVersions\.AndroidApiLevel)?(\d+)", build),
        # What Godot called autoloads: the managers the service locator builds.
        "managers": len(re.findall(r"public static \w+ \w+ \{ get; private set; \}", locator)),
        "sprites": len(list((ROOT / "Assets/Resources/Art").rglob("*.png"))),
        "sounds": len(list((ROOT / "Assets/Resources/Audio").rglob("*.wav"))),
        "definitions": len(list((ROOT / "Assets/Resources/Content").rglob("*.asset"))),
        "scenes": len(re.findall(r"Assets/Scenes/\w+\.unity", settings)),
        "prefabs": len(list((ROOT / "Assets/Resources/Prefabs").glob("*.prefab"))),
        "palette": len(PALETTE),
        "glyphs": int(_one(r"chars count=(\d+)", font)),
        "stages": len(re.findall(r'^echo "(\d+)\. ', sweep, re.M)),
        # Content counts, so the PROSE cannot go stale either. The first draft
        # of this page wrote "all sixteen sounds" and "four real minigames" as
        # words, which is the same bug as a hardcoded table — it just takes
        # longer to notice, because nobody proofreads a sentence for arithmetic.
        "worlds": _count("WorldDefinition"),
        "relics": _count("RelicDefinition"),
        "pets": _count("PetDefinition"),
        "minigames": _count("MinigameDefinition"),
        "slots": _count("SlotDefinition"),
    }


def _count(kind: str) -> int:
    return len(list((ROOT / "Assets/Resources/Content" / kind).glob("*.asset")))


# Small counts read as words in a sentence and as digits in a table. Deriving
# the number and then spelling it keeps the prose readable without giving up
# the property that makes it worth generating — that it cannot go stale.
_WORDS = ("zero", "one", "two", "three", "four", "five", "six", "seven",
          "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen",
          "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty")


def words(n: int) -> str:
    return _WORDS[n] if 0 <= n < len(_WORDS) else f"{n:,}"


def _one(pattern: str, text: str) -> str:
    match = re.search(pattern, text)
    if match is None:
        raise SystemExit(f"make_docs: nothing matched {pattern!r}")
    return match.group(1)


def tagline() -> str:
    """The short description, taken from the store listing that ships it."""
    listing = (ROOT / "production/store-listing.md").read_text(encoding="utf-8")
    section = listing.split("## Short description")[1]
    return section.split("```")[1].strip()


# --- the site -----------------------------------------------------------------


def css() -> str:
    """One stylesheet, every colour an index into the palette.

    image-rendering:pixelated is not decoration. The icon is a 32x32 image shown
    at 128px, and a browser's default smooth upscale would do to it exactly what
    the old sprite shader did to the creatures: average away the pixels that
    are the artwork.
    """
    p = PALETTE
    return f"""  :root {{ color-scheme: dark; }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0 auto; padding:3.5rem 1.25rem 4rem; max-width:44rem;
    font:15px/1.7 ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas,
      "Liberation Mono", monospace;
    background:{p['void']}; color:{p['bone']}; }}
  header {{ text-align:center; margin-bottom:3rem; }}
  img.mark {{ width:128px; height:128px; image-rendering:pixelated;
    image-rendering:crisp-edges; }}
  h1 {{ font-size:1.75rem; letter-spacing:.08em; margin:1.25rem 0 .5rem;
    color:{p['ivory']}; text-transform:uppercase; }}
  h2 {{ font-size:.95rem; letter-spacing:.14em; text-transform:uppercase;
    color:{p['crimson']}; margin:2.5rem 0 .9rem; }}
  p.lead {{ color:{p['ash']}; margin:0; }}
  a {{ color:{p['crimson']}; }}
  a:hover {{ color:{p['ivory']}; }}
  hr {{ border:0; border-top:2px solid {p['blood']}; margin:2.5rem 0; }}
  table {{ border-collapse:collapse; width:100%; }}
  td {{ border-bottom:1px solid {p['iron']}; padding:.5rem .25rem; }}
  td.n {{ text-align:right; color:{p['ivory']}; white-space:nowrap; }}
  ul {{ list-style:none; padding:0; }}
  li {{ border-bottom:1px solid {p['iron']}; padding:.5rem .25rem; }}
  li::before {{ content:"\\2022  "; color:{p['crimson']}; }}
  .swatches {{ display:flex; flex-wrap:wrap; gap:0; margin:.5rem 0 0; }}
  .swatches i {{ width:2rem; height:2rem; display:block; }}
  footer {{ margin-top:3rem; color:{p['ash']}; font-size:.85rem;
    text-align:center; }}"""


def mark() -> str:
    """The real app icon, inlined. Same bytes the launcher shows."""
    raw = (ROOT / "Assets/Icons/launcher_192.png").read_bytes()
    return base64.b64encode(raw).decode("ascii")


def index_html() -> str:
    f = facts()
    swatches = "".join(
        f'<i style="background:{value}" title="{name} {value}"></i>'
        for name, value in PALETTE.items()
    )
    rows = "\n".join(
        f'<tr><td>{label}</td><td class="n">{value}</td></tr>'
        for label, value in [
            ("Screens", f["scenes"]),
            ("Managers", f["managers"]),
            ("Content definitions", f["definitions"]),
            ("Generated sprites", f["sprites"]),
            ("Generated sounds", f["sounds"]),
            ("Palette colours", f["palette"]),
            ("Font glyphs", f["glyphs"]),
            ("Validation stages", f["stages"]),
        ]
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vanta Eclipse</title>
<meta name="description" content="{tagline()}">
<style>
{css()}
</style>
</head>
<body>
<header>
<img class="mark" alt="Vanta Eclipse" src="data:image/png;base64,{mark()}">
<h1>Vanta Eclipse</h1>
<p class="lead">{tagline()}</p>
</header>

<h2>What it is</h2>
<p>An idle RPG for Android, built in Unity {f["unity"]}. Tap to strike, or unlock
the auto-attacker and let your hero fight without you. {words(f["worlds"])}
worlds, a boss on every tenth gate, {words(f["slots"])} equipment slots,
{words(f["relics"])} relics, {words(f["pets"])} pets, an arcade of
{words(f["minigames"])} real minigames, and a prestige reset that makes the next
run faster than the last.</p>
<p>No paywall, no energy meter, no timer blocking a door. Plays in portrait,
one-handed, offline.</p>

<h2>The art is generated</h2>
<p>Every sprite, the bitmap font, the icons and all {f["sounds"]} sounds are
produced by programs in <code>tools/</code> rather than drawn or recorded. A
palette change is one edit and one command, not {f["sprites"]} files reopened by
hand. The palette is closed at {f["palette"]} colours and the validation sweep
fails on any pixel outside it — and on any asset that no longer matches the
program that draws it.</p>
<div class="swatches">{swatches}</div>

<h2>By the numbers</h2>
<table>
{rows}
</table>

<h2>Links</h2>
<ul>
<li><a href="https://github.com/kidriqrif/Vanta-Eclipse">Source on GitHub</a></li>
<li><a href="privacy-policy.html">Privacy policy</a></li>
</ul>

<hr>
<footer>
Version {f["version"]} &middot; Android {f["min_sdk"]}+ &middot;
targets API {f["target_sdk"]}<br>
This page is generated by <code>tools/make_docs.py</code>.
</footer>
</body>
</html>
"""


# --- the privacy policy's styling ---------------------------------------------


def restyled_privacy(current: str) -> str:
    """Swap in the palette stylesheet, leave every word of the policy alone."""
    return re.sub(
        r"<style>.*?</style>",
        "<style>\n%s\n</style>" % css(),
        current,
        count=1,
        flags=re.S,
    )


# --- the README block ---------------------------------------------------------


def readme_block() -> str:
    f = facts()
    return "\n".join([
        BEGIN,
        "",
        f"**Version {f['version']}** &middot; Unity {f['unity']} &middot; "
        f"Android {f['min_sdk']}+, targets API {f['target_sdk']}",
        "",
        "| | |",
        "| --- | --- |",
        f"| Screens | {f['scenes']} |",
        f"| Managers | {f['managers']} |",
        f"| Content definitions (`.asset`) | {f['definitions']} |",
        f"| Generated sprites | {f['sprites']} |",
        f"| Generated sounds | {f['sounds']} |",
        f"| Palette colours | {f['palette']} |",
        f"| Font glyphs | {f['glyphs']} |",
        f"| Validation stages | {f['stages']} |",
        "",
        "Every number above is read from the file that defines it and refreshed",
        "by `tools/make_docs.py`; `tools/check_docs.py` fails the sweep if this",
        "block drifts from the code.",
        "",
        END,
    ])


def spliced_readme(current: str) -> str:
    block = readme_block()
    if BEGIN in current and END in current:
        head, rest = current.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return f"{head}{block}{tail}"
    # First run: place it under the opening paragraph, before the first heading.
    marker = "\n## "
    at = current.find(marker)
    if at == -1:
        return f"{current.rstrip()}\n\n{block}\n"
    return f"{current[:at].rstrip()}\n\n{block}\n{current[at:]}"


# --- entry points -------------------------------------------------------------


def render() -> dict[str, str]:
    """{repository-relative path: the content it should have}.

    Shared by make_docs.py and check_docs.py so the generator and the check can
    never disagree about what "correct" is — the failure that would make the
    check theatre.
    """
    return {
        "docs/index.html": index_html(),
        "docs/privacy-policy.html": restyled_privacy(
            (ROOT / "docs/privacy-policy.html").read_text(encoding="utf-8")
        ),
        "README.md": spliced_readme(
            (ROOT / "README.md").read_text(encoding="utf-8")
        ),
    }


def main() -> int:
    changed = 0
    for name, content in render().items():
        path = ROOT / name
        before = path.read_text(encoding="utf-8") if path.exists() else None
        if before == content:
            print(f"  {name:34s} unchanged")
            continue
        path.write_text(content, encoding="utf-8", newline="\n")
        changed += 1
        print(f"  {name:34s} UPDATED")
    print(f"{changed} file(s) rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
