// Ported from scripts/managers/audio_manager.gd
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using VantaEclipse.Data;

namespace VantaEclipse.Core
{
    /// <summary>
    /// Every sound the game makes.
    ///
    /// Listens to the EventBus and nothing else. No UI script asks for a sound,
    /// which is why adding audio to a finished game touched no screen: the
    /// events that deserve a sound were already being raised for the UI.
    ///
    /// Sounds are generated by tools/make_audio.py — see that file for the
    /// design rules behind them.
    /// </summary>
    public sealed class AudioManager : MonoBehaviour
    {
        /// <summary>Voices per sound. Four is enough for the tap to overlap
        /// itself at the fastest attack speed in the game without cutting its
        /// own tail off.</summary>
        public const int Voices = 4;

        /// <summary>
        /// Minimum gap between two plays of the SAME sound, in seconds.
        ///
        /// Layering a clip over itself does not make it twice as loud, it makes
        /// it clip: every sound peaks at 0.72, and two in the same frame is
        /// 1.44 into a bus that stops at 1.0. Not hypothetical — CombatManager
        /// raises BossFightWon, WorldManager answers it by raising
        /// WorldUnlocked, and both map to the fanfare, so beating a world boss
        /// distorted the single biggest moment the game has.
        ///
        /// Sounds gap independently of each other. A crit landing 10ms after a
        /// tap still plays both, because two different sounds read as variety;
        /// it is one sound repeating that reads as a fault.
        /// </summary>
        static readonly Dictionary<string, float> RepeatGap = new()
        {
            // Swift Hunt plus Twin Fang drives the auto-attacker faster than
            // the tap can decay. Twenty taps a second is a buzz, not feedback,
            // and it is the fastest way to make someone mute a game.
            { "tap", 0.055f },
            // Kills arrive in bursts at high attack speed for the same reason.
            { "death", 0.12f },
            // Long, loud, and triggered by two separate events on one frame.
            { "fanfare", 0.4f },
            { "boss", 0.4f },
            // A kill can drop an item, a relic and a pet at once.
            { "loot", 0.06f },
            // A screen change and a modal opening can both land on one frame;
            // this is what makes them one whoosh instead of two.
            { "whoosh", 0.12f },
            // Several Journal goals can complete on the same kill.
            { "goal", 0.15f },
            { "claim", 0.15f },
            { "levelup", 0.1f },
            // Short, so it can be quick, but long enough that a double-tap on
            // one button is one click.
            { "click", 0.04f },
            // Long, and each marks a moment that cannot happen twice in half a
            // second.
            { "boss_warn", 0.5f },
            { "fail", 0.5f },
            { "eclipse", 1f },
        };

        /// <summary>Enough to stop one frame's duplicates without ever being
        /// audible as a dropped sound.</summary>
        public const float DefaultRepeatGap = 0.03f;

        /// <summary>Per-shot pitch jitter. Without it a held finger produces
        /// the same 70ms sample forty times in a row, which stops reading as
        /// impact and starts reading as a fault.</summary>
        public const float PitchJitter = 0.08f;

        static readonly Dictionary<string, string> Sfx = new()
        {
            { "tap", "tap_hit" },
            { "crit", "crit_hit" },
            { "death", "enemy_death" },
            { "boss", "boss_defeat" },
            { "fanfare", "fanfare" },
            { "confirm", "confirm" },
            { "loot", "loot" },
            { "boss_warn", "boss_warn" },
            { "fail", "fail" },
            { "whoosh", "whoosh" },
            { "goal", "goal" },
            { "claim", "claim" },
            { "levelup", "levelup" },
            { "eclipse", "eclipse" },
            { "click", "click" },
        };

        const string MusicClip = "ambient_void";

        readonly Dictionary<string, AudioSource[]> _voices = new();
        readonly Dictionary<string, int> _nextVoice = new();
        readonly Dictionary<string, float> _lastPlayed = new();
        AudioSource _music;

        /// <summary>Where the drone had got to when the app was backgrounded,
        /// so resuming picks the loop up rather than restarting its swell from
        /// the top every time the player glances at a notification.</summary>
        float _musicPosition;

        internal static AudioManager Spawn()
        {
            var go = new GameObject("[AudioManager]");
            DontDestroyOnLoad(go);
            var audio = go.AddComponent<AudioManager>();
            audio.BuildVoices();
            audio.BuildMusic();
            audio.ConnectEvents();
            SceneManager.sceneLoaded += audio.OnSceneLoaded;
            return audio;
        }

        void BuildVoices()
        {
            foreach (var pair in Sfx)
            {
                var clip = Resources.Load<AudioClip>($"Audio/sfx/{pair.Value}");
                if (clip == null)
                {
                    Debug.LogError($"AudioManager: missing sound Audio/sfx/{pair.Value}");
                    continue;
                }
                var pool = new AudioSource[Voices];
                for (int i = 0; i < Voices; i++)
                {
                    var source = gameObject.AddComponent<AudioSource>();
                    source.clip = clip;
                    source.playOnAwake = false;
                    // Ignoring the listener pause is the equivalent of
                    // PROCESS_MODE_ALWAYS: the offline modal and every confirm
                    // scrim pause the game, and a purchase made from a modal
                    // must not be silent.
                    source.ignoreListenerPause = true;
                    pool[i] = source;
                }
                _voices[pair.Key] = pool;
                _nextVoice[pair.Key] = 0;
            }
        }

        void BuildMusic()
        {
            var clip = Resources.Load<AudioClip>($"Audio/music/{MusicClip}");
            if (clip == null)
            {
                Debug.LogError($"AudioManager: missing music Audio/music/{MusicClip}");
                return;
            }
            _music = gameObject.AddComponent<AudioSource>();
            _music.clip = clip;
            // Unity loops the whole clip natively, so the loop-point surgery
            // the Godot version needed is gone. That code existed because an
            // imported .wav defaults to a one-shot and a loop_end left at 0 is
            // a ZERO-LENGTH loop, not "play to the end" — the track started and
            // stopped in the same frame, and the only symptom was silence,
            // indistinguishable from the game having no music at all.
            _music.loop = true;
            _music.playOnAwake = false;
            _music.ignoreListenerPause = true;
            _music.Play();
        }

        // --- Public ---------------------------------------------------------

        /// <summary>Silence everything and remember where the music was.
        /// Public because the test harness drives it directly — the Android
        /// lifecycle callbacks it normally answers cannot be raised from a
        /// headless run.</summary>
        public void Suspend()
        {
            if (_music != null && _music.isPlaying)
            {
                _musicPosition = _music.time;
                _music.Stop();
            }
            foreach (var pool in _voices.Values)
                foreach (var source in pool)
                    source.Stop();
        }

        /// <summary>Pick the drone back up where it left off. One-shots are not
        /// resumed: a hit sound the player never heard is not worth playing
        /// three minutes late.</summary>
        public void Resume()
        {
            if (_music == null || _music.isPlaying) return;
            _music.time = _musicPosition;
            _music.Play();
        }

        /// <summary>Play a sound by id. Drops a repeat of the same sound inside
        /// its RepeatGap, round-robins the voice pool so a sound never cuts its
        /// own tail, and jitters pitch so repeats do not sound mechanical.</summary>
        public void Play(string id, float pitch = 1f)
        {
            if (!_voices.TryGetValue(id, out var pool) || pool.Length == 0) return;

            // Unscaled: the gap must elapse in real time even while the game is
            // paused behind a modal.
            float now = Time.unscaledTime;
            float gap = RepeatGap.TryGetValue(id, out var g) ? g : DefaultRepeatGap;
            if (_lastPlayed.TryGetValue(id, out var last) && now - last < gap) return;
            _lastPlayed[id] = now;

            int index = _nextVoice[id];
            _nextVoice[id] = (index + 1) % pool.Length;

            var source = pool[index];
            source.pitch = pitch * (1f + Random.Range(-PitchJitter, PitchJitter));
            source.Play();
        }

        /// <summary>
        /// Give every button a click without a single UI script asking for one.
        ///
        /// The alternative was 65 handlers across 22 screens each remembering
        /// to make a noise, and the one that forgot would be found by a player.
        /// This keeps the property the rest of this file has: AudioManager
        /// listens, nothing announces.
        ///
        /// Godot could hook the tree's node_added and catch every button ever
        /// created, including ones written next year. Unity has no such signal,
        /// so this runs per scene load and UI that builds rows at runtime must
        /// call Adopt() on what it spawned. That is a real regression from the
        /// original and the reason this method is public rather than private.
        /// </summary>
        public void Adopt(GameObject root)
        {
            if (root == null) return;
            foreach (var button in root.GetComponentsInChildren<Button>(includeInactive: true))
            {
                // A disabled button never fires onClick, so an unaffordable
                // upgrade stays silent on its own without anything here having
                // to know what it costs.
                button.onClick.AddListener(OnAnyButtonPressed);
            }
        }

        void OnSceneLoaded(Scene scene, LoadSceneMode mode)
        {
            foreach (var root in scene.GetRootGameObjects()) Adopt(root);
        }

        void OnAnyButtonPressed() => Play("click");

        // --- Handlers --------------------------------------------------------

        void ConnectEvents()
        {
            var bus = Game.Events;

            bus.EnemyDamaged += OnEnemyDamaged;
            bus.EnemyDied += (level, kills) => Play("death");
            bus.BossFightWon += OnBossWon;

            // Earned moments. All rare, all worth the same fanfare — a player
            // should learn one sound that means "you got something permanent".
            bus.WorldUnlocked += world => Play("fanfare");
            bus.AutoAttackUnlocked += () => Play("fanfare");
            bus.RelicsAwakened += () => Play("fanfare");
            bus.PetEvolved += (id, stage) => Play("fanfare");
            bus.EclipseAvailable += () => Play("fanfare");
            bus.ArcadeUnlocked += () => Play("fanfare");

            // The exception to the one-fanfare rule. An Eclipse is the biggest
            // thing a player ever chooses to do, and sharing the generic unlock
            // sound made it land like picking up a relic.
            bus.EclipsePerformed += (reward, count) => Play("eclipse");

            // Bosses. The countdown is the only fail state in the game, and
            // both ends of it made no sound at all. Silence on failure reads as
            // the game not having noticed.
            bus.BossFightStarted += (def, lvl, hp, secs) => Play("boss_warn");
            bus.BossFightFailed += level => Play("fail");

            // The Journal, which was silent end to end.
            bus.GoalCompleted += id => Play("goal");
            bus.GoalClaimed += (id, rewardText) => Play("claim");

            // Collecting something already earned, as opposed to being handed a
            // drop.
            bus.AdRewardGranted += (placement, amount) => Play("claim");
            bus.OfflineRewardsReady += (amount, away, capped) => Play("claim");
            bus.PetLeveled += (id, level) => Play("levelup");
            bus.MinigameFinished += OnMinigameFinished;

            // Navigation. One file at three pitches: opening, closing, changing
            // screen.
            bus.UiOverlayOpened += () => Play("whoosh");
            bus.UiOverlayClosed += () => Play("whoosh", 0.8f);
            bus.SceneTransitionStarted += path => Play("whoosh", 0.9f);

            // Acquisitions.
            bus.ItemDropped += item => Play("loot");
            bus.RelicDropped += id => Play("loot");
            bus.PetUnlocked += id => Play("loot");

            // Deliberate actions the player took, which need a confirmation
            // they landed.
            bus.UpgradePurchased += (id, level) => Play("confirm");
            bus.ItemEquipped += slot => Play("confirm");
            bus.SkillPurchased += (id, level) => Play("confirm");
            bus.ActiveRelicChanged += id => Play("confirm");
            bus.ActivePetChanged += id => Play("confirm");
            bus.CosmeticEquipped += id => Play("confirm");
            bus.PurchaseCompleted += id => Play("confirm");
        }

        void OnEnemyDamaged(float amount, bool isCrit, float hp, float maxHp)
        {
            // No rate limiting here — Play() gaps each sound against itself. A
            // crit therefore still lands in the middle of a stream of taps,
            // which matters: it is the moment worth hearing, and suppressing it
            // would mean the bigger the fight, the less the payoff registers.
            Play(isCrit ? "crit" : "tap");
        }

        void OnBossWon(int level, float payout, bool isWorldBoss)
        {
            Play("boss");
            if (isWorldBoss) Play("fanfare");
        }

        /// <summary>An Arcade run ending. A win borrows the Journal's progress
        /// sound and a loss borrows the boss timer's, deliberately: the Arcade
        /// is a side room, and giving it private sounds would teach the player
        /// two vocabularies for one meaning. QUIT is silent — forfeiting is not
        /// an outcome worth scoring.</summary>
        void OnMinigameFinished(string id, int outcome, float payout)
        {
            if (outcome == (int)MinigameOutcome.Win) Play("goal");
            else if (outcome == (int)MinigameOutcome.Loss) Play("fail");
        }
    }

    /// <summary>How an Arcade run ended.</summary>
    public enum MinigameOutcome { Win, Loss, Quit }
}
